name: Build & Deploy to Aliyun OSS

on:
  push:
    branches: [ aliyun-oss ]
  pull_request:
    branches: [ aliyun-oss ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Aliyun
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Install npm dependencies
        run: npm install

      - name: Run build task
        run: npm run build --if-present

      - name: upload files to OSS
        uses: fangbinwei/aliyun-oss-website-action@v1.4.0
        with:
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
          bucket: ${{ secrets.BUCKET_NAME }}
          endpoint: ${{ secrets.BUCKET_ENDPOINT }}
          folder: ${{ secrets.BUCKET_FOLDER }}